// @reforce/core 的错误码表（ADR 0013 决议 2，#289）。每个持有码的包一律把表声明在 src/error-codes.ts：
// 读者找「这个包有哪些码」只有一处要看，@reforce/cli 的 explain/code-registry 也只认这一条路径。
// 数组是唯一真相、union 从它派生——此前 union 与各处的字面量各写各的，删一个成员或写一个不在
// 表里的码 typecheck 都不报。码表不集中到注册包：那会造成反向依赖。
//
// 它不是「全框架的码表」，只是容器自己的闭集——框架包各自持有自己的码，因此 ReforceError 的
// 类型参数上界只能是 string，跨包的码由各自的类字面量声明（ADR 0009 起 CLI 侧就按 string 消费）。
export const coreErrorCodes = [
  "EARLY_BEAN_ACCESS",
  "BEAN_CREATION_FAILED",
  "BEAN_LIFECYCLE_FAILED",
  "BEAN_DISPOSAL_FAILED",
  "APPLICATION_START_FAILED",
  "APPLICATION_CLEANUP_FAILED",
  "CONFIG_BINDING_FAILED",
  "REQUEST_CONTEXT_MISSING",
  "UNREGISTERED_BEAN_TARGET",
  "APPLICATION_CONTEXT_STATE",
  "INVALID_GENERATED_DEFINITION",
  "INTERCEPTOR_REENTERED",
  // 公开 API 的参数守卫（ADR 0013 决议 3，#292）。此前全是裸 TypeError：无码、无 help、
  // 不进识别，而这恰恰是新手最常撞的一层。带 CORE_ 前缀是决议 2 对**新码**的要求；上面
  // 那批存量码一律不改名。
  "CORE_INVALID_BEAN_OPTIONS",
  "CORE_MISSING_BEAN_FACTORY",
  "CORE_INVALID_BEAN_SCOPE",
  "CORE_REQUEST_BEAN_DISPOSE",
  "CORE_INVALID_BEAN_DISPOSE",
  "CORE_INVALID_BEAN_PRIMARY",
  "CORE_INVALID_BEAN_QUALIFIER",
  "CORE_INVALID_QUALIFIER_NAME",
  "CORE_INVALID_ORDER_VALUE",
  "CORE_INVALID_APPLICATION_OPTIONS",
  "CORE_MISSING_APPLICATION_STARTERS",
  "CORE_INVALID_METHOD_MARKER_KEY",
  "CORE_METHOD_MARKER_ARITY",
  "CORE_METHOD_MARKER_TARGET",
  "CORE_INVALID_INTERCEPTOR_OPTIONS",
  "CORE_INVALID_INTERCEPTOR_MARKER",
  "CORE_INVALID_INTERCEPTOR_PHASE",
  "CORE_INVALID_INTERCEPTOR_ORDER",
  "CORE_INVALID_REQUEST_SEEDS",
  "CORE_INVALID_REQUEST_SEED",
  "CORE_SEED_TARGET_NOT_REQUEST_SCOPED",
  "CORE_SEED_INSTANCE_TYPE_MISMATCH",
  "CORE_DUPLICATE_REQUEST_SEED",
  "CORE_BEAN_FACTORY_RETURN",
] as const;

export type CoreErrorCode = (typeof coreErrorCodes)[number];
