import type { DiagnosticArticle } from "@/explain/codes";

// CLI 失败码的长文（ADR 0013 决议 5 的长文缺口收口，#297）。存量十二码全部来自
// @reforce/runtime 的 cliFailureCodes（reporter 打给用户的失败码词汇表，ADR 0013 决议 2，
// #289）。
//
// 单独成文件，判据仍是读者场景（codes.ts 文件头）：这十二条回答的是第五种——「reforce 命令
// 本身失败」。读者坐在终端前看着一条失败的 build/dev/start/lib 输出，能做的动作（重跑、
// 停掉占着租约的进程、别往产物树里伸手、读 caused-by 链）跟其余四组都不重叠。
//
// 每条断言在源码里指得出依据：回退码语义在 @reforce/runtime 的 reporter.ts
// （resolveFailureCode：错误自带的码永远赢，回退码只兜住无码异常，ADR 0013 决议 4），租约在
// @reforce/cli 的 project/lease.ts，目录事务在 project/directory-transaction.ts，启动守卫在
// start/artifact.ts，崩溃接管在 @reforce/runtime 的 crash-takeover.ts 与
// shutdown-controller.ts。

// 两个目录事务码共用正文（同 argument-articles / transaction-articles 的码组做法）：它们是
// 同一个 DirectoryTransactionError 类、同一套 journal 协议，kind 字段是唯一区别，分开写只会
// 产出两篇互相重复的散文；summary 仍逐码一句。
const directoryTransaction = [
  "Reforce publishes its two output trees the way a database commits. The compiler's generated",
  "output (.reforce/generated — beans.ts, bootstrap.ts, manifest.json, qualifiers.d.ts,",
  "routes.json, routes.ts, weaving.json) and the production bundle (dist/, which must contain",
  "main.mjs) are each replaced as one directory transaction: the new tree is written and",
  "fsynced into a staging directory, a journal under .reforce/transactions records each step,",
  "the old tree is renamed to a backup, staging is renamed into place, the published result is",
  "read back and verified against the journal's hashes, and only then are backup and journal",
  "removed. This code means one of those steps failed. The transaction was rolled forward or",
  "back, but the commit you asked for did not land.",
  "",
  "The point of the ceremony is what you are spared: a crash — kill -9, OOM, power loss — at",
  "any step leaves either the complete new generation or the complete old one, never a torn",
  "tree, and reforce start refuses to run a dist that a transaction left half-swapped.",
  "Recovery runs automatically at the start of every build and dev session, replaying the",
  "journal to whichever complete generation exists.",
  "",
  "What usually breaks a step, most likely first:",
  "",
  "  1. Something else has its hands in the tree. Antivirus scanners, file indexers, and sync",
  "     clients hold files open mid-rename (Windows renames are retried, but not forever),",
  "     and tools that write into .reforce/generated or dist add entries the exact file-set",
  "     validation refuses. Symbolic links and non-regular files anywhere in either tree are",
  "     rejected outright. Keep other writers out of both directories.",
  "  2. The filesystem itself failed — out of space, permissions, I/O errors. The caused-by",
  "     chain carries the original error; fix that and rerun.",
  "  3. Recovery found no complete generation: the new tree and the previous one both fail",
  "     verification, which takes damage from outside the protocol. Both trees are compiler",
  "     output with nothing hand-written in them, so the way out is to delete the damaged",
  "     tree together with any leftover staging/backup directories and the entries under",
  "     .reforce/transactions, then run reforce build to regenerate everything.",
  "",
  "Start with the cheap step: run reforce build again. Recovery is part of the run, and a",
  "transient cause — a scanner that has since let go of the file — clears on the rerun. Only",
  "a failure that repeats with the same message is worth the deeper look above.",
];

export const cliArticles: Readonly<Record<string, DiagnosticArticle>> = {
  CLI_USAGE_ERROR: {
    summary:
      "The reforce invocation itself was rejected — bad arguments, or a query matching nothing.",
    article: [
      "This code never comes out of a build or your application: the CLI rejected the invocation",
      "itself, before any command logic ran or any file was touched. It has exactly two sources,",
      "and the message tells you which one you hit.",
      "",
      "The first source is the argument parser. An unknown command, an unknown or malformed option,",
      "a missing required argument, or an out-of-range value for a choice option (--error-format",
      "only takes its listed modes) all land here, with the command's usage help printed alongside.",
      "Options are per-command and are written after the command name:",
      "reforce build --error-format=json, not reforce --error-format=json build.",
      "",
      "The second source is an explain query that resolves to nothing. reforce explain accepts a",
      "diagnostic code, a bean id, an export name, a contract display name, or a route query",
      "('/path' or 'GET /path'). A query that matches none of them fails with this code, and the",
      "message carries the candidates: known beans for a bean-shaped query, known routes for a",
      "route-shaped one. One special case is worth knowing: a query that merely looks like an",
      "error code (ALL_CAPS shape) but is in no code table is almost always a typo — check the",
      "spelling against the code printed in the failure line you started from. Every registered",
      "code has a long-form article, so a real code always answers with one.",
      "",
      "Fix the invocation and run it again: nothing was compiled, written, or started, so there is",
      "no state to clean up. reforce --help lists the commands; reforce <command> --help lists",
      "each command's options.",
    ],
  },
  PACKAGE_EXPORTS_INVALID: {
    summary:
      "The starter compiled, but package.json exports does not map ./reforce-meta correctly.",
    article: [
      "reforce lib and reforce meta check report this. Under reforce lib the starter library",
      "compiled and nothing was written: the exports check runs before the write, so a package",
      "that cannot deliver its meta never gets one on disk. What failed is the delivery contract:",
      "consumers locate a starter's meta through the package's exports map, so both commands",
      "verify that package.json declares",
      "",
      '  "exports": { "./reforce-meta": "./reforce-meta.json" }',
      "",
      "The CLI checks and refuses; it never edits your package.json — rewriting author manifests is",
      "the bundler plugin's job, so from the CLI the fix is always a manual edit. The message says",
      "which of the three checks failed:",
      "",
      "  1. package.json cannot be read as JSON — fix the syntax error first.",
      '  2. package.json must declare an exports map — add the "exports" object.',
      '  3. exports must map "./reforce-meta" to "./reforce-meta.json" — the subpath is missing or',
      "     points somewhere else.",
      "",
      "Two declaration shapes are accepted: the plain string target shown above, or a conditions",
      'object whose "default" condition is exactly that target. Patterns, array fallbacks, and',
      "deeper condition nesting are rejected even where a package manager would resolve them:",
      "their meaning depends on resolver semantics the tooling does not interpret, so the",
      "contract insists on the direct form.",
      "",
      "After the edit, run reforce lib again. The meta file itself is already in place; the",
      "rerun only needs to see the exports map reach it.",
    ],
  },
  STARTER_META_OUT_OF_DATE: {
    summary:
      "reforce lib --check found the committed reforce-meta.json differs from what the source produces.",
    article: [
      "Only reforce lib --check reports this. The check mode compiles the starter exactly like a",
      "normal run, then compares the bytes it would write against the bytes already on disk -",
      "and writes nothing either way. A difference means the committed meta no longer describes",
      "the source: someone added, removed, or reshaped a bean and did not regenerate.",
      "",
      "This matters because the meta is what consumers read. A stale meta does not fail the",
      "starter's own build; it fails in someone else's application, as a missing bean or a wrong",
      "dependency edge, with nothing pointing back at the starter. Running the check in CI turns",
      "that into a failure in the repository that caused it.",
      "",
      "The fix is always the same: run reforce lib in the package and commit the result. If the",
      "file is missing entirely, that is the same finding - a starter without a meta is invisible",
      "to consumers, so an absent file and a stale one get one answer.",
      "",
      "The check runs after the exports check, so if package.json does not map ./reforce-meta you",
      "get PACKAGE_EXPORTS_INVALID first. Fix that one first: a meta that consumers cannot locate",
      "is not made better by being up to date.",
    ],
  },
  PROJECT_BUSY: {
    summary: "Another reforce process holds this project's lease, so the command refused to run.",
    article: [
      "Every reforce command that touches a project first takes a lease under .reforce/lease, so",
      "that two processes can never write the same generated output or run against a half-written",
      "tree. build and dev take the writer lease (they rewrite .reforce/generated and dist);",
      "start takes a reader lease (it runs dist and must not have it swapped underneath it).",
      "Writers exclude everyone; a reader only excludes writers. This code means the lease could",
      "not be acquired — or, mid-run, turned out to no longer be yours.",
      "",
      "Liveness is probed, not guessed from a lock file: each lease record carries a loopback",
      "endpoint, and an acquirer challenges it. An owner that answers is live, and the acquire",
      "fails immediately with this code. An owner that is provably dead is quarantined and its",
      "lease taken over, so a crashed process never blocks a project for good — the next acquire",
      "cleans it up. Only contention on the short acquisition gate itself is retried, for about",
      "five seconds, before it too gives up with this code.",
      "",
      "The usual causes, most likely first:",
      "",
      "  1. Another reforce process really is running against this project — a dev watcher in",
      "     another terminal, a start instance, a CI job. reforce build while reforce start",
      "     serves the same project is the classic case. Stop it, or point --project elsewhere.",
      "  2. The probe could not decide. A firewall or sandbox that blocks loopback connections",
      "     makes a dead owner look merely unreachable, and an unreachable owner is treated as",
      "     live — taking over a lease you cannot disprove would risk two writers.",
      "  3. A record under .reforce/lease is corrupt, or an interrupted directory transaction's",
      "     journal belongs to a writer this process has no proof of having replaced. Both refuse",
      "     rather than guess.",
      "",
      "If you are sure nothing is running, simply run the command again: dead-owner recovery is",
      "part of every acquire. Only if it still refuses — and you can rule out every live reforce",
      "process — is removing .reforce/lease by hand a last resort.",
    ],
  },
  GENERATED_TRANSACTION_FAILED: {
    summary: "The atomic replacement of .reforce/generated failed; the commit did not land.",
    article: directoryTransaction,
  },
  DIST_TRANSACTION_FAILED: {
    summary: "The atomic replacement of the production dist/ tree failed; the commit did not land.",
    article: directoryTransaction,
  },
  BUILD_FAILED: {
    summary:
      "The build pipeline threw an exception carrying no code of its own — not a source problem.",
    article: [
      "BUILD_FAILED is a fallback, and that is the most useful thing to know about it. When a",
      "command fails, the reporter first asks the error itself for a code: framework errors carry",
      "their own (PROJECT_BUSY, GENERATED_TRANSACTION_FAILED, DIST_TRANSACTION_FAILED, and the",
      "rest), and compiler diagnostics keep their diagnostic code. Only an error that answers",
      "with nothing lands on BUILD_FAILED. So this code does not mean your source has a problem:",
      "anything the compiler can attribute to your source is reported as error[CODE] diagnostics",
      "with file and span, and the command exits non-zero without ever printing BUILD_FAILED.",
      "",
      "What it does mean: an exception escaped the build pipeline outside the diagnostic path.",
      "The commands that report it are build ('Application build failed.'), lib ('Library build",
      "failed.'), and dev — at command level ('Development command failed.') and per rebuild in",
      "watch mode ('Development compilation failed.', after which the last healthy application",
      "keeps running while you fix things).",
      "",
      "The identity of the failure is in the caused-by chain under the headline, root cause last",
      "and highlighted. The usual suspects, most likely first:",
      "",
      "  1. The bundler or a build-time dependency threw: a plugin crash, an import the bundler",
      "     (not the compiler) could not resolve, a native module that failed to load.",
      "  2. The environment interfered: file-watcher limits, permissions, disk space, files",
      "     changed or deleted mid-build.",
      "  3. Neither of those — a bare exception from inside the toolchain with no code and no",
      "     environmental cause is a bug worth reporting with the --verbose output attached.",
      "",
      "Rerun with --verbose to unfold the stack frames that are folded away by default; the",
      "frames say whose code threw, which is the fastest way to tell case 1 from case 3.",
    ],
  },
  ARTIFACT_INVALID: {
    summary: "A command that only reads generated output found it missing, incomplete, or unsafe.",
    article: [
      "The commands that only read generated output guard it before trusting it. reforce start",
      "runs dist/; reforce explain and reforce openapi read .reforce/generated (manifest.json,",
      "weaving.json, routes.json); reforce dev validates each rebuild's assets before reloading",
      "the child. This code means the artifact the command was pointed at is missing, incomplete,",
      "or not something the CLI is willing to execute. Nothing was run — which is the point:",
      "starting a torn or foreign artifact fails later and stranger than refusing up front.",
      "",
      "The message names the specific check:",
      "",
      "  - No generated manifest / weaving table / route table — the project has never been built",
      "    in this directory. Run reforce build (or reforce dev) first.",
      "  - '… is not valid. Rebuild the application.' — the file exists but fails schema",
      "    validation: a partial write, a hand edit, or output from an incompatible version.",
      "  - 'incomplete dist transaction' — a build was interrupted mid-publish and dist/ may be",
      "    half-swapped. reforce build recovers it; start deliberately refuses to guess.",
      "  - Symbolic links, non-regular files, or a dist that is itself a symlink — the production",
      "    tree must contain ordinary files only, and its entry point (dist/main.mjs) must",
      "    resolve inside the project. Artifacts that traveled through a copy step that",
      "    introduced links or dropped files trip these.",
      "",
      "Ways out, in the order to try them:",
      "",
      "  1. Run reforce build in the project directory. It regenerates .reforce/generated and",
      "     dist/, and on the way in it completes or rolls back any interrupted transaction.",
      "  2. If the artifact came from somewhere else, transfer it as plain regular files — no",
      "     symlinks — and keep dist/ exactly as build wrote it.",
      "  3. Do not hand-edit anything under .reforce or dist. The schemas are validated on every",
      "     read, so even an edit that keeps the JSON parseable still fails here.",
    ],
  },
  BOOTSTRAP_FAILED: {
    summary: "The application threw while starting up, before it ever reached running.",
    article: [
      "Bootstrap is the stretch between process start and 'the application is running': the",
      "generated bootstrap module binds configuration, builds the container, constructs every",
      "singleton in dependency order, and starts whatever the installed starters bring up. An",
      "exception thrown anywhere in that stretch is caught in one place, the application is shut",
      "down cleanly (whatever was already constructed gets closed), and the process exits 1 with",
      "this report. In production the message is 'Application bootstrap failed.'; under dev it is",
      "'Development child bootstrap failed.', and the dev supervisor restarts the child once per",
      "build before giving up with CHILD_FAILED.",
      "",
      "Like the other lifecycle codes, this one is a fallback: an error thrown during bootstrap",
      "that carries its own reforce code reports as that code instead — CONFIG_BINDING_FAILED,",
      "the environment failing a config schema, is the common one and has its own article. Seeing",
      "BOOTSTRAP_FAILED therefore means the exception came from code the framework does not own:",
      "a bean constructor or factory, a lifecycle hook, a driver dialing a backing service.",
      "",
      "The root cause is the last, highlighted line of the caused-by chain. The frequent ones:",
      "",
      "  1. EADDRINUSE — the port is taken, usually by a previous instance that has not finished",
      "     dying, sometimes by an unrelated service.",
      "  2. ECONNREFUSED and relatives — the database, broker, or cache the application connects",
      "     to during startup is not reachable from here.",
      "  3. A throw in your own construction code. The stack (unfold it with --verbose) names the",
      "     module; fix the constructor or factory it points at.",
    ],
  },
  HMR_FATAL: {
    summary:
      "A hot reload in reforce dev failed mid-swap; the dev child restarted from a clean process.",
    article: [
      "Only reforce dev reports this, and only from a hot reload. When a rebuild lands and",
      "validates, the dev parent tells the child over IPC, and the child runs the swap: check for",
      "the update, close the current application, apply the new modules, bootstrap the",
      "replacement. This code means that sequence threw. It is deliberately fatal rather than",
      "retried in place: after a failed check or apply the underlying HMR runtime has no way back",
      "to a clean state, so limping on would poison every later reload. The child shuts down",
      "instead — and the parent supervisor restarts it once per build, so the usual visible",
      "outcome is one restart into a fresh process, not a dead dev session.",
      "",
      "Which step threw is in the caused-by chain:",
      "",
      "  1. The replacement's bootstrap failed — by far the most common. The new code throws",
      "     while constructing beans; in the freshly restarted child the same error reports as",
      "     BOOTSTRAP_FAILED, whose article has the checklist. Fix the code and save again.",
      "  2. The old application's close() failed. A dispose hook that throws, or a resource that",
      "     cannot shut down, kills the swap even though the new code is fine. Close hooks run on",
      "     every reload in dev, so they need to tolerate a live, mid-session application.",
      "  3. The update transfer itself failed — hot-update assets missing or unreadable, which",
      "     usually means something outside reforce deleted or rewrote the build output between",
      "     the rebuild landing and the child fetching it.",
      "",
      "If the failure persists in the restarted child, the restart budget (one per build) runs",
      "out and the session ends with CHILD_FAILED. The fix is whatever the chain names, not the",
      "reload machinery: restarting reforce dev reproduces the same error at bootstrap whenever",
      "the code itself is at fault.",
    ],
  },
  CHILD_FAILED: {
    summary:
      "The supervised application child process failed; its own report above holds the cause.",
    article: [
      "dev and start do not run your application in their own process: they supervise a child",
      "that does. CHILD_FAILED is the parent's verdict — the child process failed and the parent",
      "has no more moves — and it is therefore almost never the whole story. The child shares the",
      "parent's stderr, so the child's own failure report, with its own code, is printed above",
      "this one. Read upward first.",
      "",
      "Under reforce dev the message is 'Development child exhausted its restart budget.' A dev",
      "child that dies is restarted once per build; a second death on the same build ends the",
      "session, because restarting identical code again would produce an identical crash. The",
      "budget resets on every new validated build, so the loop is: read the child's report above,",
      "fix the code, save — the next build starts a fresh child with a fresh budget.",
      "",
      "Under reforce start the message wraps whichever way the production child failed:",
      "",
      "  1. 'Production child exited with code N.' — the application terminated on its own; its",
      "     report above says why (a bootstrap failure, a crash, a shutdown error).",
      "  2. 'Production child did not exit within Nms of the shutdown request and was killed.' —",
      "     you asked it to stop, the 30-second grace period ran out, and it was force-killed.",
      "     Something in the application cannot finish closing: a close hook that never settles,",
      "     a connection pool that never drains.",
      "  3. A broken startup handshake — the child never reported its lease participant record,",
      "     which means the entry the parent launched is not a reforce production build.",
      "",
      "start also uses this code when acknowledging over IPC, to a parent of its own, that the",
      "child ended non-zero; there it is a status on the wire, not a fresh failure.",
    ],
  },
  SHUTDOWN_FAILED: {
    summary:
      "The command's work may have finished, but releasing its resources did not go cleanly.",
    article: [
      "Shutdown is its own phase with its own code because 'the work succeeded' and 'everything",
      "was released' are separate claims. Every command runs a fixed finalizer — flush the",
      "reporter, close the compiler session, release the project lease, stop a leftover child —",
      "and every step runs even when an earlier one throws; the failures are collected and",
      "reported together at the end. Inside a running application the same applies to close():",
      "dispose hooks and server shutdown get their chance, and a throw there is 'Application",
      "shutdown failed.'. The exit code is 1 even when the command's real work was fine, because",
      "a leaked resource behind an exit 0 would never be noticed.",
      "",
      "So first check whether the run also failed for a primary reason: when it did, that failure",
      "leads the aggregated caused-by chain and this code is only the trailer. A run that failed",
      "only at shutdown usually traces to:",
      "",
      "  1. A close() or dispose hook in the application throwing or rejecting. These run on",
      "     every Ctrl-C and every dev reload; they need to tolerate a partially started",
      "     application.",
      "  2. The reporter's output stream dying mid-flush — the terminal or pipe on the other end",
      "     went away first. Harmless to the work; the code exists so it is at least on record.",
      "  3. Lease release contention — the release could not be confirmed. This self-heals:",
      "     liveness is probed, and a record left behind by an exited process is quarantined by",
      "     the next command's acquire.",
      "",
      "One rare variant deserves its own note: '<command> command failed outside its shutdown",
      "boundary.' means an exception escaped the command's own error handling entirely, which is",
      "a CLI bug worth reporting, not something in your project.",
      "",
      "Nothing here invalidates what the command produced: a build that reported success before a",
      "shutdown failure still committed a complete artifact. Fix the hook or ignore the dead",
      "pipe, and rerun only if you need the clean exit code.",
    ],
  },
  UNCAUGHT_EXCEPTION: {
    summary: "An exception escaped every handler in the running application; the process exited 1.",
    article: [
      "The runtime installs a crash handler in both the production process and the dev child,",
      "taking over Node's uncaughtException default. Taking over obliges it to give back exactly",
      "what Node would have done — the stack on stderr and exit code 1 — plus what Node would",
      "not: when the application has framework logging, the crash is written through it as a",
      "structured fatal record (the error under 'err'), log sinks are flushed on a two-second",
      "budget so the record is not lost with the process, and only then does the process exit.",
      "The message says which kind arrived: 'uncaught exception' (a throw with no catch above it",
      "— a timer callback, an event handler) or 'unhandled rejection' (a promise that rejected",
      "with nobody awaiting or catching it).",
      "",
      "This code appears on stderr in exactly two situations: the crash happened before the",
      "application's logger existed (mid-bootstrap, or the application wires no framework",
      "logging), or the logger itself threw while recording the crash. Otherwise the crash lands",
      "in your logs as the fatal record, and stderr only carries the stack.",
      "",
      "What to do with it:",
      "",
      "  1. Read the stack under the report. Frames from node internals and the framework are",
      "     folded into counts by default; --verbose (or REFORCE_VERBOSE=1) prints every frame.",
      "  2. An unhandled rejection is always a floating promise. Find the call that produced it",
      "     and await it or attach a .catch; the stack shows where the rejected error was",
      "     created, which is usually enough to locate the un-awaited call.",
      "  3. A second line reading 'a second crash arrived while the first was still being",
      "     flushed' is deliberate: the second crash is recorded but does not restart the exit",
      "     sequence, so diagnose the first one — it is the preserved scene.",
      "",
      "This code never comes from the framework's own guard rails — those throw coded errors that",
      "report as themselves. It marks an exception that escaped every handler, which is why the",
      "fix is always in the code (yours or a dependency's) that let it escape.",
    ],
  },
};
