import type { DiagnosticArticle } from "@/explain/codes";

// 容器与 web 管线运行期错误码的长文（ADR 0013 决议 5 的长文缺口收口，#297）。覆盖
// coreErrorCodes 里的 11 个存量运行时码（决议 2 前缀纪律之前的老码）与 webErrorCodes 里的
// 4 个存量管线码。
//
// 单独成文件，判据仍是读者场景（codes.ts 文件头）：codes.ts 回答「编译不过」，
// argument-articles 回答「运行时被自己写的调用参数拦住」，transaction-articles 回答「运行时
// 被事务护栏拦住」。这十五条回答的是第四种——「运行时框架自身的生命周期或请求管线出错」：
// 读者手上是一个启动失败/请求炸掉/停机不干净的应用，能做的动作（读 cause、重建产物、把 I/O
// 挪进生命周期钩子、修 close 钩子的幂等性）跟前三组都不重叠。
//
// 每条断言在源码里指得出依据：容器侧在 @reforce/core 的 runtime/context.ts、
// runtime/bean-resolver.ts、runtime/lifecycle-runner.ts、generated/validation.ts 与
// interception/invoke.ts；web 侧在 @reforce/web-core 的 execution/web-application.ts、
// execution/slot-execution.ts、execution/serialization.ts、execution/error-dispatch.ts 与
// generated/validation.ts。

export const runtimeArticles: Readonly<Record<string, DiagnosticArticle>> = {
  // —— 容器生命周期与请求作用域（@reforce/core）——
  APPLICATION_START_FAILED: {
    summary:
      "The Application Context could not start; the real failure travels as this error's cause.",
    article: [
      "Startup is one transaction-like sequence: bind every configuration class, construct every",
      "singleton in the compiler's order, then run the onContextStart() hooks. If any step fails,",
      "the container rolls back — every resource successfully created up to that point is released",
      "exactly once — and the whole attempt is reported as this single envelope. The process is not",
      "half-started afterwards: the Context is in the failed state and cannot be reused.",
      "",
      "The envelope itself says nothing about what went wrong; its cause does, and the cause always",
      "carries a code of its own:",
      "",
      "  CONFIG_BINDING_FAILED         the environment did not satisfy a config class's schema.",
      "  BEAN_CREATION_FAILED          a constructor or factory threw; its own cause is the throw.",
      '  BEAN_LIFECYCLE_FAILED         an onContextStart() hook threw, phase "start".',
      "  INVALID_GENERATED_DEFINITION  the generated artifact failed the container's checks.",
      "",
      "Even a throw the framework does not recognize is wrapped into BEAN_CREATION_FAILED first, so",
      "walking the cause chain always ends at the original exception. The CLI reporter does this",
      "walk for you: it prints the first help text it finds along the chain.",
      "",
      "The errors array is a separate story: it holds failures from the rollback itself — close",
      "hooks and disposers that broke while undoing the partial start. It never masks the cause;",
      "startup keeps its original error even when rollback also fails. A non-empty errors array",
      "therefore means two bugs: whatever stopped startup, and shutdown code that cannot cope with",
      "being run against a partially started application. Fix the cause first, but do not ignore",
      "the second — it is the same code path a normal shutdown uses.",
    ],
  },
  BEAN_CREATION_FAILED: {
    summary: "A Bean's constructor or factory threw while the container was building it.",
    article: [
      "The container did not fail here — your constructor or factory did, and the container wrapped",
      "the throw so it can say which Bean was being built and how it got there. The original",
      "exception is preserved unchanged as the cause: read that first, it is the actual story. The",
      "wrapper adds beanId and dependencyPath — the chain of constructors that was open, outermost",
      "first, ending at the Bean whose code threw.",
      "",
      "Wrapping happens exactly once. A failure deep in a dependency chain surfaces as one",
      "BEAN_CREATION_FAILED for the Bean that threw, not a stack of them for every consumer above",
      "it, so beanId always names the guilty party rather than whoever asked for it.",
      "",
      "Where you see it depends on when construction ran. Singletons are built during startup, so",
      "there it arrives as the cause of APPLICATION_START_FAILED. Request-scoped Beans are built at",
      "the start of each request, so there it rejects the runInRequestScope call — the application",
      "keeps running and only that request fails.",
      "",
      "Two usual causes, in order of likelihood:",
      "",
      "  1. The constructor's own logic threw — a precondition it checks, a value it derives, a",
      "     library it calls during setup. The cause is that exception verbatim; fix it where it",
      "     says.",
      "  2. The constructor is doing work that does not belong in a constructor. Singleton",
      "     construction is deliberately synchronous — a constructor cannot await anything — so",
      "     connection handshakes, file reads and other I/O belong in an onContextStart() hook",
      "     (implement OnContextStart), which is async and runs after every Bean is constructed.",
      "     Constructors assign; hooks connect.",
    ],
  },
  BEAN_LIFECYCLE_FAILED: {
    summary: "A Bean's onContextStart() or onContextClose() lifecycle hook threw.",
    article: [
      "Lifecycle hooks are where a Bean touches the outside world. Constructors are deliberately",
      "synchronous — they cannot await anything — so connection handshakes, schema warm-up and every",
      "other piece of real I/O live in onContextStart(), and the matching teardown lives in",
      "onContextClose(). This code wraps a throw from one of those hooks; the phase field says",
      "which, and the cause is the hook's own exception, unchanged. Read the cause first — the",
      "framework's contribution is only the Bean name and the phase.",
      "",
      "The two phases surface differently:",
      "",
      "  start   Hooks run one at a time, in the generated order, after every singleton is",
      "          constructed. The first failure stops startup: this error becomes the cause of",
      "          APPLICATION_START_FAILED, and everything already constructed is rolled back —",
      "          close hooks and disposers run once each before the process gives up.",
      "  close   Hooks run while the Context shuts down. A failure here does not stop cleanup:",
      "          every remaining hook still runs, and all failures are collected into the errors",
      "          array of APPLICATION_CLEANUP_FAILED (or of APPLICATION_START_FAILED, when the",
      "          cleanup was a rollback), in execution order.",
      "",
      "A start-phase failure is usually the environment, not the code: the database or broker the",
      "hook connects to is unreachable, or its credentials and addresses — already bound and",
      "validated as configuration — point somewhere that is not answering. A close-phase failure is",
      "usually the code: a hook that cannot tolerate the resource being already gone. Close hooks",
      "run during rollbacks and racing shutdowns too, so write them to be safe to call once under",
      "any circumstances — closing an already-closed pool should be a no-op, not a throw.",
    ],
  },
  BEAN_DISPOSAL_FAILED: {
    summary: "A factory Bean's dispose() function threw while the Context was cleaning up.",
    article: [
      "A factory Bean declared with defineBean({ create, dispose }) hands the container two halves",
      "of one contract: create builds the instance, dispose releases whatever create acquired. At",
      "cleanup the container calls dispose(instance) once; a throw from it becomes this error, with",
      "your disposer's exception preserved unchanged as the cause. Read the cause first — the",
      "framework adds only the Bean id.",
      "",
      "You never catch this code on its own. Cleanup does not stop at the first failure: every",
      "remaining close hook and disposer still runs, and all failures arrive together in the errors",
      "array of APPLICATION_CLEANUP_FAILED (a normal shutdown) or APPLICATION_START_FAILED (the",
      "rollback after a failed start). Its class-Bean sibling in that array is",
      'BEAN_LIFECYCLE_FAILED with phase "close".',
      "",
      "The usual cause is a disposer that assumes the resource is still in the state create left it",
      "in. Disposers also run during rollbacks and racing shutdowns, so the resource may already be",
      "closed, half-initialized, or shared with another registration that got to it first. Write",
      "dispose to be safe to call once in any state — quietly return when there is nothing left to",
      "release — and keep it to releasing what create acquired; anything more belongs in an",
      "onContextClose() hook on a class Bean, where ordering against other Beans is explicit.",
      "",
      "Only singletons have disposers. Request-scoped instances are dropped when their request",
      "ends, so a request-scoped defineBean with dispose is rejected up front",
      "(CORE_REQUEST_BEAN_DISPOSE) and can never reach this code.",
    ],
  },
  APPLICATION_CLEANUP_FAILED: {
    summary: "One or more Beans failed to release their resources while the Context was closing.",
    article: [
      "Closing the Context runs every registered cleanup action — each class Bean's",
      "onContextClose() hook and each factory Bean's dispose() — in an order the compiler generated,",
      "the same order every run. A failure does not stop the pass: releasing the database pool still",
      "matters even if the cache client before it threw. So the container runs everything, collects",
      "every failure, and throws this single aggregate at the end.",
      "",
      "There is no single cause to look at. The errors array holds one entry per failed action, in",
      'execution order: BEAN_LIFECYCLE_FAILED with phase "close" for a class Bean\'s hook,',
      "BEAN_DISPOSAL_FAILED for a factory's disposer. Each entry names its Bean and carries that",
      "hook's own exception as its cause — iterate the array and treat every entry as its own bug.",
      "",
      "Despite the throw, the shutdown itself is done: every action was attempted exactly once, all",
      "close() callers share this one result, and the Context ends in the closed state either way.",
      "Nothing is left to retry — what this error asks for is fixing the hooks before the next run.",
      "",
      "The usual failure shape is a hook that assumes the world is still fully alive: it closes a",
      "resource that is already gone, or reaches through a client whose connection another hook",
      "just tore down. Cleanup also runs as the rollback of a failed start, against a partially",
      "constructed application, so hooks must tolerate resources in any state. Make each close and",
      "dispose safe to call once under any circumstances — return quietly when there is nothing to",
      "release — and keep each one to its own Bean's resources.",
    ],
  },
  EARLY_BEAN_ACCESS: {
    summary:
      "A Bean was read while its constructor was still running, before the instance was complete.",
    article: [
      "The container constructs singletons one at a time, in an order the compiler computed so that",
      "every ordinary dependency is finished before its consumer starts. A constructor is therefore",
      "the only window in which a Bean exists but is not done — and this code means something read a",
      "Bean inside that window. The instance it would have received is half-initialized, so the",
      "container refuses to hand it out. The error carries beanId and constructionPath: the chain of",
      "constructors that was open at that moment, ending at the Bean that was read too early.",
      "",
      "Three situations produce it, in the order they show up in practice:",
      "",
      "  1. A constructor in a dependency cycle used a dependency instead of just storing it. The",
      "     compiler breaks constructor cycles by handing one side a proxy; storing the proxy is",
      "     fine, but calling a method or reading a property on it before the target finishes lands",
      "     here. Keep the constructor to assignments, and move the first real use into a method or",
      "     into an onContextStart() lifecycle hook (implement OnContextStart) — hooks run only",
      "     after every singleton is constructed, so the cycle is closed by then.",
      "  2. A Lazy<T> was unwrapped too early: lazy.get() inside a constructor while the target is",
      "     itself mid-construction. Lazy defers when the target is built; it does not suspend the",
      "     rule that nobody may see a Bean half-built.",
      "  3. During a request, a request-scoped Bean reached forward — through a singleton's method",
      "     chain — to a request Bean that comes later in the same request plan. The plan constructs",
      "     all request Beans up front, so reading forward during that pass is the one way to catch",
      "     one missing.",
      "",
      "constructionPath is the debugging tool: it lists the constructors that were open, outermost",
      "first, and the last two entries are the edge to break. Either defer that access as above, or",
      "restructure so the cycle disappears and no proxy is involved at all.",
    ],
  },
  APPLICATION_CONTEXT_STATE: {
    summary: "A Context operation was called in a lifecycle state that cannot serve it.",
    article: [
      "The Application Context is a one-way state machine: created, starting, running, closing,",
      "closed — with failed as the terminal state of a start that did not survive. Each public",
      "operation is only meaningful in some of those states, and rather than block, queue, or",
      "return something half-true, the Context names the mismatch: the message carries both the",
      "operation and the state it found.",
      "",
      "What each operation requires:",
      "",
      "  start               only from created. Start is one-shot: a second call lands here, as",
      "                      does starting again after close. Share the first start's promise",
      "                      instead of calling twice.",
      "  get                 only while running. Before start() resolves the singletons are not all",
      "                      constructed; after close() they are gone.",
      "  runInRequestScope   only while running — a request needs the full singleton set beneath it.",
      "  lazy.get,           these live on handles that Beans hold, so they keep working while the",
      "  cycle-proxy access  Context is alive — including during ordered cleanup — and land here",
      "                      once it is closed.",
      "",
      "The usual causes, in order of likelihood:",
      "",
      "  1. Use-after-close: a handle — the context itself, a Lazy, a cycle proxy — captured by",
      "     something long-lived (a timer, an in-flight task, a global) and used after shutdown, or",
      "     racing it. Tie such work into the shutdown order with an onContextClose() hook so it",
      "     stops before the Beans it uses are released.",
      "  2. Use-before-ready: context.get called before start() was awaited, often from module",
      "     top-level code or from inside a constructor reaching back into the container.",
      "     Dependencies belong in constructor parameters, where the compiler orders them; the",
      "     running state exists precisely because get cannot answer earlier.",
      "  3. A start that failed earlier: after APPLICATION_START_FAILED the state is failed, and",
      "     every later operation reports this code. The original startup error is the one to fix;",
      "     these are just its echo.",
    ],
  },
  REQUEST_CONTEXT_MISSING: {
    summary: "Request-scoped state was read while no request scope was active.",
    article: [
      "Request-scoped Beans live in a per-request store. runInRequestScope opens one, mounts it on",
      "the async context, constructs the request Beans, and runs your callback; the store exists",
      "exactly for that callback and the await chain growing out of it. In a web application the",
      "engine does this around each request, so a route handler and everything it awaits into can",
      "read request state. Anything running outside such a chain has no store — there is no 'the",
      "current request' to answer with — and the read fails with this code instead of returning a",
      "stale or foreign request's value.",
      "",
      "The message tells you which side of the API was involved. A Current<T> handle names both",
      "ends — 'Current dependency of consumer onto target' — because the handle is held by a",
      "singleton and the edge identifies exactly which field was read. A plain context.get on a",
      "request-scoped class can only name the target.",
      "",
      "Three usual causes, in the order they occur in practice:",
      "",
      "  1. The read happens in code that never runs inside a request: a constructor, an",
      "     onContextStart() hook, a scheduled job, a CLI path. Request state cannot exist there.",
      "     Pass the needed values in as arguments from a request-side caller instead.",
      "  2. The read is in request-side code, but on a callback that escaped the request's async",
      "     chain — a setTimeout/setInterval body, an event-emitter listener, work pushed to a",
      "     queue and picked up later. The async context does not follow those hops. Call .get()",
      "     while the request is still live and hand the plain value to the deferred work.",
      "  3. A test calls into code that reads request state without opening a scope. Wrap the call:",
      "     await context.runInRequestScope(seeds, () => ...), seeding the request Beans the code",
      "     under test expects.",
    ],
  },
  UNREGISTERED_BEAN_TARGET: {
    summary:
      "context.get, or a request seed, named a class the container has no Bean registered for.",
    article: [
      "The container resolves a target by object identity: the generated definition maps the exact",
      "class object (or the exact object defineBean returned) that the compiler registered onto a",
      "Bean id. The class you passed is not in that map. Nothing is matched by name or by shape —",
      "a class that looks identical but is a different object is, to the container, a stranger.",
      "",
      "That identity rule orders the likely causes:",
      "",
      "  1. The class was never compiled in as a provider. It is missing @Injectable, or its file",
      "     is outside the leaf tsconfig's compiled source set, so the compiler never saw it — no",
      "     import or re-export is required. Fix the annotation or the include patterns, rebuild.",
      "  2. The build is stale: the class was added or renamed after the generated artifact was",
      "     last written. Rebuild.",
      "  3. Same source, two objects. The module containing the class is loaded twice — one import",
      "     resolving to src and another to dist, a dependency duplicated in the module graph, or a",
      "     test importing the class from a different path than the generated registration uses.",
      "     Each copy is a distinct class object, and only the registered one resolves. Align the",
      "     import paths so a single module instance serves both the registration and the call.",
      "",
      "The same check guards runInRequestScope seeds: a seed's target must name a registered Bean",
      "before the request-scope rules even look at it, so an unknown seed target reports this code",
      "rather than a seed error.",
      "",
      "For everything else about the target, resolution is compile-time work: inside a compiled",
      "application the injection graph was checked at build time, and this code at runtime almost",
      "always means the artifact and the running module graph disagree rather than a wiring mistake.",
    ],
  },
  INVALID_GENERATED_DEFINITION: {
    summary: "The generated application definition failed the container's own consistency checks.",
    article: [
      "The container never trusts the artifact it boots from. Before anything runs, it re-validates",
      "the compiler's entire output against the wire protocol — every registration's exact fields,",
      "every Bean id, every dependency edge and its scope rules, every construction and lifecycle",
      "plan, down to the schema version — and a few lookups keep defending at runtime, when a plan",
      "names a Bean or a generated resolver asks for a dependency. The detail after the colon names",
      "the exact field that failed.",
      "",
      "The compiler cannot emit a definition that fails these checks; they mirror its own rules.",
      "So this code never means your application code is wrong — it means the artifact and the",
      "runtime that loaded it disagree. The realistic ways that happens:",
      "",
      "  1. The artifact is stale: sources changed, generated output did not. Rebuild.",
      "  2. Version skew: the compiler that wrote the artifact and the @reforce/core that is",
      "     loading it come from different releases, or @reforce/core is installed twice and the",
      "     definition was built against the other copy. Align the versions, reinstall, rebuild.",
      "  3. The generated files were edited, patched, or transformed by something after the",
      "     compiler — a bundler rewrite, a codemod, a hand fix that outlived its moment.",
      "  4. The runtime entry points (createApplicationContext, a factory registration) are being",
      "     fed hand-written input, in a harness or an experiment. They validate it like any",
      "     artifact.",
      "",
      "Start with a clean rebuild. If the code survives a clean rebuild with matching versions, the",
      "generated output is being produced or modified by something other than the current compiler,",
      "and that producer is the thing to chase — the detail string tells you which field to look at",
      "in the emitted file.",
    ],
  },
  INTERCEPTOR_REENTERED: {
    summary: "An interceptor called next() a second time on the same invocation.",
    article: [
      "Method interception is an onion: each interceptor wraps the layers inside it and gets one",
      "next() to reach them. One is the contract — the chain is not re-entrant, and that is a",
      "deliberate v1 decision, not a missing feature. By the time your first next() returns, every",
      "inner layer has finished its after-phase, and the transaction boundary the chain may have",
      "opened has already committed or rolled back. A second next() would rerun the method inside a",
      "boundary that is already settled: a retried write would land outside the transaction whose",
      "protection was the point. The framework fails loudly instead, naming the Bean and method.",
      "",
      "The two ways code ends up here:",
      "",
      "  1. A retry loop inside intercept(), wrapped around next(). Retrying is legitimate; this is",
      "     just the wrong altitude for it. Move the retry to the call site — the code that invokes",
      "     the woven method — where each attempt opens a fresh chain, fresh interceptor state, and",
      "     a fresh transaction.",
      "  2. next() invoked concurrently — a Promise.all over calls that share one next, or a stored",
      "     next() invoked from a callback while the first call is still in flight. Same guard,",
      "     same reasoning: one chain, one traversal.",
      "",
      "One discipline keeps this error visible: a fallback interceptor that catches everything and",
      "returns a degraded value must let framework errors through first —",
      "",
      "  try { return await next() } catch (error) {",
      "    if (isReforceError(error)) { throw error }",
      "    return fallback",
      "  }",
      "",
      "Without that rethrow, this guard and the transaction guards are swallowed by your own",
      "fallback, and the symptom becomes 'no error, wrong data' — the one outcome worse than the",
      "exception.",
    ],
  },
  // —— web 请求管线（@reforce/web-core）——
  INVALID_ROUTE_TABLE: {
    summary:
      "The generated route table failed the runtime's contract check, so the application refused to start.",
    article: [
      "The route table is the wire between the compiler and the runtime: reforce compilation writes",
      "out every route's method, path, controller binding, input slots, response declaration,",
      "middleware chain and error handler list as one generated object (schemaVersion 3). At startup,",
      "before any engine adapter mounts a single route, createWebApplication() re-validates that",
      "object field by field as untrusted input: the top-level keys are closed, every vocabulary",
      "(HTTP methods, middleware phases and mounts, slot kinds, response kinds) is a closed set that",
      "rejects unknown values, and the schema version is a hard gate. This code is that validation",
      "failing — the application refuses to boot; no request was involved.",
      "",
      "The message carries the exact field that broke the contract, as a path like",
      "routeTable.routes[2].response.kind. Read it first; it decides which case you are in:",
      "",
      "  1. A stale or mismatched artifact. The usual trigger is upgrading @reforce/web-core or the",
      "     compiler without regenerating: an old table fails the schemaVersion gate, and a newer",
      "     runtime rejects fields an old compiler never wrote. Rebuild the project — a table the",
      "     current compiler just produced always passes this check.",
      "  2. A hand-assembled table. Test harnesses and anything else that constructs the table",
      "     without the compiler are held to the same contract as generated output; fix the field",
      "     the message names.",
      "  3. Two routes with the same method and path shape. Parameter names do not disambiguate",
      "     (GET /users/:id and GET /users/:name are the same shape), and empty segments are folded",
      "     first, so /p, /p/ and //p collide as well — every engine is required to treat those as",
      "     one path. This is the runtime twin of the compile-time DUPLICATE_ROUTE check, and it is",
      "     a hard error on purpose: a duplicate means one handler can never be reached, and a",
      "     silently dead route is worse than a failed boot. Rename or merge one of the routes.",
      "",
      "Two more throw sites share this code, both at startup bean resolution: a middleware or error",
      "handler Bean whose resolved instance does not implement handle(). The compiler only registers",
      "classes that satisfy those contracts, so reaching either at runtime again means the artifact",
      "no longer matches its sources — rebuild before debugging anything else.",
    ],
  },
  MIDDLEWARE_REENTERED: {
    summary:
      "A middleware called next() a second time on one request; the chain refuses to re-run.",
    article: [
      "A middleware's handle(context, next) sits on an onion: next() runs everything inside it — the",
      "remaining middleware, input validation, the handler, response serialization — and hands back",
      "the Response. The chain is assembled once per route at startup, and each layer's next() may",
      "run exactly once per request. This code is a layer calling it a second time.",
      "",
      "The refusal is structural. By the time the second call happens, the inner layers have already",
      "run to completion: re-entering would execute the handler again — a second database write for",
      "the same request — behind the caller's back. The guard sits on each layer's own next closure",
      "and flips before the first await, so even two synchronous back-to-back calls are caught. The",
      "error names the middleware Bean that misbehaved (by beanId, which uniquely identifies the",
      "layer — a layer number would not) plus the route's method and path, so the search starts at",
      "the right class.",
      "",
      "The usual shapes of the bug, in order of likelihood:",
      "",
      "  1. A retry loop around await next(). Retrying 'the rest of the request' means re-running",
      "     the handler; if a downstream call is flaky, retry that call inside the service that",
      "     makes it, not the chain.",
      "  2. next() called again from a catch or finally after the first call threw. The first call",
      "     already consumed the chain — recovery here means building and returning a Response, or",
      "     rethrowing so an @ErrorHandler can answer, never running the pipeline again.",
      "  3. Two branches that each call next(), reached together by some input.",
      "",
      "The fix is the same restructuring in every case: call next() at most once, keep whatever must",
      "happen afterwards after that single await (that is what the help line under the error says),",
      "and on the paths that do not call it, return a Response of your own. Middleware that only",
      "observes should await next(), look at the response, and return it.",
      "",
      "Unless one of your outer middleware or an @ErrorHandler catches it (handlers can dispatch on",
      'code "MIDDLEWARE_REENTERED"), the error falls to the framework fallback: a 500',
      "application/problem+json response carrying an errorId that matches the server log entry.",
    ],
  },
  REQUEST_VALIDATION_FAILED: {
    summary:
      "A request input slot failed its contract's validation, so the handler was never invoked.",
    article: [
      "A route's handler parameters each declare which part of the request they read — Body<…>,",
      "Param<…>, Query<…>, Header<…> — and what shape it must have. The compiler turns each of those",
      "contracts into a decoder (or wires in the Standard Schema value the contract traces to), and",
      "the runtime runs them after every middleware and before the handler. This code is one of those",
      "decoders saying no: the handler never ran, and nothing it guards was touched.",
      "",
      "The failure is treated as a request-level fact, not a framework fault. The framework's own",
      "fallback renders it as a 400 application/problem+json document with three extension members:",
      "",
      '  { "type": "about:blank", "title": "Bad Request", "status": 400,',
      '    "code": "REQUEST_VALIDATION_FAILED", "source": "body", "issues": [ … ] }',
      "",
      "source names the slot that failed first (body, params, query or header); issues carries",
      "every schema issue's message and path — never the offending value, because request payloads",
      "carry credentials. All slots are checked before the error is thrown, so one round trip hands",
      "the caller every problem at once instead of one slot per retry.",
      "",
      "Three reasons you are looking at it, in order of likelihood:",
      "",
      "  1. The caller really sent something the contract rejects. This is the code working as",
      "     intended — 400 is the answer, and the issue messages are the caller's fix list.",
      "  2. The contract is stricter than you meant. The decoder is generated from the contract type",
      "     on the handler parameter (or from the schema it traces to), so the real fix lives at",
      "     compile time: adjust the type or schema, recompile, and the decoder follows. There is no",
      "     runtime knob to loosen it.",
      "  3. The body slot's transport rules bit a legitimate caller. A Body slot accepts exactly",
      "     application/json (charset parameters are fine; +json suffixes and form encodings are",
      "     refused on purpose), a non-empty body, and valid JSON — each failure lands here with",
      "     source 'body'. Forms and uploads sit outside the Body contract deliberately: read them",
      "     yourself with request.formData() instead of declaring a Body slot.",
      "",
      "To change what the caller sees, register an @ErrorHandler accepting RequestValidationError:",
      "user handlers run before the fallback, and the error object exposes source and the raw",
      "issues. The 400 shape above is also what reforce's OpenAPI export publishes as the",
      "ReforceValidationProblem component, so clients may rely on it as a contract.",
    ],
  },
  RESPONSE_SERIALIZATION_FAILED: {
    summary:
      "A handler's return value could not become an HTTP response under the route's contract.",
    article: [
      "Every route carries a response declaration the compiler wrote into the route table, derived",
      "from the handler's return type, an @ResponseSchema, or inference. Its kind decides what the",
      "runtime does with the return value:",
      "",
      "  table        the contract expanded into a whitelist projection encoder plus a status code —",
      "               only declared fields go out on the wire.",
      "  free-form    no contract could be declared or inferred: the value is serialized as-is, with",
      "               no projection and no whitelist.",
      "  passthrough  the handler owns the response. It must return a Response (sent untouched) or",
      "               nothing (an empty body — 204 unless a status was declared).",
      "",
      "A handler that returns an actual Response is passed through untouched under every kind: that",
      "is the escape hatch for streaming, redirects and custom content types, and the framework",
      "neither projects it nor overrides its status.",
      "",
      "This code means the return value could not become a response under those rules. The three",
      "triggers, in order of likelihood:",
      "",
      "  1. A passthrough route's handler returned a data value. Passthrough is what a route gets",
      "     when its declared or inferred return is Response (or void), so there is no encoder to",
      "     apply to a plain object. Either return a Response, or declare a data-shaped return type",
      "     or @ResponseSchema and recompile so the route gets an encoder — that fix lives at",
      "     compile time, on the contract, not in a runtime hook.",
      "  2. An error handler returned a data value without a declared @ResponseStatus. A response",
      "     needs a status and a match-all handler declares none, so the framework swaps the",
      "     in-flight error for this code and keeps dispatching down the handler chain. Declare",
      "     @ResponseStatus on the handler, or build and return the Response yourself.",
      "  3. The value — or what the route's encoder projected from it — serializes to nothing:",
      "     JSON.stringify yields no output for undefined, functions and bare symbols. Returning",
      "     undefined from a body-producing route is the common shape; return the value, or make",
      "     the route void if there is genuinely no body.",
      "",
      "What the client sees: the error is dispatched like any other, and if no handler accepts it,",
      "the fallback answers 500 application/problem+json with an errorId matching the server log —",
      "the response is replaced whole, never sent half-serialized. Two near-misses that are not this",
      "code: bigint and Date are normalized to strings by table encoders and survive raw",
      "serialization (bigint via a retry, Date via toJSON), and a circular structure propagates as",
      "the engine's own TypeError instead.",
    ],
  },
};
